### ISSUE TITLE
meta info

### ISSUE THREAD

**Issue by blakejohnson** [BBN-Q/Auspex#6]
- [x] ~~Convert SegmentNum sweeps to directly accept axis descriptors~~
- [x] Construct an experiment from a QGL meta JSON file
    - [x] Enable filter pipeline downstream from receivers
    - [x] Update seqfile of AWGs
    - [x] Construct appropriate `SegmentNum` sweep

**Comment by blakejohnson** [comment]
Possible implement bullet item 2 by allowing `QubitExpFactory.create()` to take a `meta_info` argument.

**Comment by grahamrow** [comment]
Wen withe the ExpFactory route. Good progress here, though it hasn't been field-tested.

**Comment by dieris** [comment]
The seqfiles on the APSs don't seem to be updated

**Comment by grahamrow** [comment]
We now expect that metafiles will be run directly with `QubitExpFactory.run(meta_info = ..)` or `QubitExpFactory.create(meta_info = ..)`. SegmentNum sweeps will never be specified manually, since they always derive from the meta_info. Moreover, I've added the method `experiment.add_qubit_sweep` which allows for trivial specification of certain types of sweeps, i.e.:

```python
exp = QubitExpFactory.create(RabiAmp(q, np.linspace(-1, 1, 11)))
exp.add_qubit_sweep("q1 measure frequency")
exp.add_qubit_sweep("q1 measure power")
exp.run_sweeps()
```
